/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Ramesh
 */
public class billpayment extends javax.swing.JFrame {
    private Object datetime;

    /**
     * Creates new form billpayment
     */
    public billpayment() {
        initComponents();
        currentdateTime();
    }
    public void currentdateTime()
    {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        Datetime.setText(dtf.format(now));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        billername = new javax.swing.JTextField();
        payfrom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        acbalance = new javax.swing.JLabel();
        Datetime = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        max = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("      PAY BILLS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 6, 293, 52));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("BACK");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 6, -1, 58));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Biller Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 119, 150, 52));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("        VIEW LIMIT");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 250, 251, 43));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("PAY From");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 299, 150, 42));

        billername.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(billername, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 119, 251, 52));

        payfrom.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(payfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 301, 251, 41));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("SELECT ACCOUNT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 369, 251, 49));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Amount");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 436, 150, 42));
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 436, 251, 42));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("PAY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 484, 111, 51));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("CANCEL");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 484, -1, 51));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("VIEW ACCOUNT BALANCE");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 354, -1, 54));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Your Account Balance is");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 426, -1, 52));

        acbalance.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        acbalance.setText("000000");
        getContentPane().add(acbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(1005, 426, 174, 52));

        Datetime.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Datetime.setText("DATE");
        getContentPane().add(Datetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 10, 346, 53));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel11.setText("LIMIT");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 118, -1, 47));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Min");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 189, 103, 42));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setText("Max");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 269, 103, -1));

        min.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        min.setText("0000");
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 196, 171, -1));

        max.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        max.setText("0000");
        getContentPane().add(max, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 259, 171, 48));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ", "Electricity", "Gas", "Internet", "School" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 188, 251, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ramesh\\OneDrive\\Pictures\\BACKGROUND.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dashboard obj = new dashboard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        min.setText("Rs.100");
        max.setText("Rs.50,000");
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        String selectedValue=jComboBox1.getSelectedItem().toString();
        billername.setText(selectedValue); 
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/banking","root","");
            String sql = "select accountnumber from account where ID =2";
            PreparedStatement ptst =  conn.prepareStatement(sql);
            ResultSet rs = ptst.executeQuery(sql);
            if(rs.next())
            {
                payfrom.setText(rs.getString("accountnumber"));
            }
            else
            {
                payfrom.setText("");
            }
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/banking","root","");
            String sql = "Select accountbalance from account where ID = 2";
            PreparedStatement ptst =conn.prepareStatement(sql);
            ResultSet rs = ptst.executeQuery(sql);
            if(rs.next())
            {
                acbalance.setText("");
            }
            else
            {
                acbalance.setText("");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/banking","root","");
            String amnt = amount.getText();
            int amntInt=Integer.parseInt(amnt);
            String billerName=billername.getText();
            String sql = "Select accountbalance from account where ID=2";
            PreparedStatement ptst = conn.prepareStatement(sql);
            ResultSet rs = ptst.executeQuery();
            if(rs.next())
            {
                acbalance.setText(rs.getString("accountbalance"));
                String accbalance= rs.getString("accountbalance");
                int accbalanceInt = Integer.parseInt(accbalance);
                if(accbalanceInt >= amntInt)
                {
                    int leftover = accbalanceInt-amntInt;
                    String sql1 = "Update account SET accountbalance='"+leftover+"'";
                    PreparedStatement ptmt = conn.prepareStatement(sql1);
                    ptmt.execute();
                    String sql2 = "insert into paybill values(?,?,?)";
                    PreparedStatement pts = conn.prepareStatement(sql2);
                    pts.setString(1,billername.getText());
                    pts.setString(2,amount.getText());
                    pts.setString(3,Datetime.getText());
                    pts.execute();
                    JOptionPane.showMessageDialog(null,"Your"+billername+"bill of amount"+amnt+"has been paid");
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Account balance is too Low");
                }
            }
                
                else
                {
                    acbalance.setText("");
                }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billpayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Datetime;
    private javax.swing.JLabel acbalance;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField billername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel max;
    private javax.swing.JLabel min;
    private javax.swing.JTextField payfrom;
    // End of variables declaration//GEN-END:variables
}
